name: Deploy PureScript and Svelte to Pages

on:
  push:
    branches:
      - main

  # allow manual trigger
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Install Purescript
        run: npm install -g purescript

      - name: Install Spago
        run: npm install -g spago

      - name: Install dependencies
        run: npm ci

      - name: Build PureScript code
        run: spago build

      - name: Bundle code
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
